# Generated by Django 5.0.1 on 2024-01-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='amount_to_pay',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
