# Generated by Django 5.0.1 on 2024-01-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loanapplication_amount_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
